### PR TITLE
Add content to README.md

### PR DESCRIPTION
**Pull request by sdelafond**
Mostly from https://www.linuxquestions.org/questions/linux-software-2/mlb-tv-in-linux-432479/page334.html#post5826059, with some extras.

### CODE REVIEW

**Comment by sdelafond** [comment]
No interest in this one ? :)

**Comment by tonycpsu** [comment]
Plenty of interest, actually -- I just have some corrections / additions I want to make.

No harm in merging this now and making those later, though.

**Comment by sdelafond** [comment]
Thanks !

BTW, mlbstreamer should enter Debian sometime soonish: https://ftp-master.debian.org/new/mlbstreamer_0.0.2-2.html :)

**Comment by tonycpsu** [comment]
Outstanding!

**Pull request merged**
