### PR TITLE
Fix to available teamcodes. 

### PR DESCRIPTION
**Pull request by eithrial**
Fixes problem with picking Los Angeles Angels streams. With code "laa" it pick stream of opponent team. It should be "ana" instead.

### CODE REVIEW

**Comment by mkomko** [comment]
I don't think the _teamCode_ is very intuitive: kca, lan, nyn, nya, etc.
I think the _fileCode_ would be okay (wasn't it that before?).

Best would be to support all codes if they are even unique.

What's the underlying problem with LAA?

**Comment by eithrial** [comment]
You are probably right. For several days I tried to pick Angel's stream now when they play with Boston. But it returns Boston's stream instead.

**Comment by tonycpsu** [comment]
I switched from using `fileCode` to `abbreviation.lower()` when I was trying to add MiLB support, because the `teamCode`s for MiLB teams aren't very useful.

The bug here is that I didn't switch to using `abbreviation` in my code for determining the preferred stream.  I'll push a fix for that shortly.

**Comment by tonycpsu** [comment]
Fixed in 73a9cc59ff72513b6c382915e91188937ccac282.

**Pull request closed without merging**
